### ISSUE TITLE
Потоки icecast2

### ISSUE THREAD

**Issue by ghost** [RadioHopeUA/Android-GolosNadii#1]
Привет, а приложение может подтягивать потоки icecast2? По типу: http://site.xy:8000/live?

**Comment by merlin-zaraza** [comment]
В приложнии используеться [ExoPlayer](https://github.com/google/ExoPlayer). Насколько мне известно ExoPlayer не поддерживает ICY. Но можеш посмотреть здесь [https://github.com/google/ExoPlayer/issues/2368](https://github.com/google/ExoPlayer/issues/2368)
